name: Build cffi wheel

on:
  push: {}

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-2019
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          repository: python-cffi/cffi
          ref: d7f750b1b1c5ea4da5aa537b9baba0e01b0ce843
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13-dev"
      - name: Install python deps
        run: |
          python -m pip install -U pip build wheel
      - name: Build cffi wheel
        run: |
          python -m build --outdir dist --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist/*.whl
  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: mkdir dist
      - uses: actions/download-artifact@v4
        with:
          path: ./dist
      - name: Release
        uses: ncipollo/release-action@1cbdc80532ba923d3d81ebd1cece305c437b8d66
        with:
          artifacts: dist/**/*.whl
